
backend = "glx";

shadow = true;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-red = 0.1;
shadow-green = 0.1;
shadow-blue = 0.1;
shadow-opacity = 0.65;
shadow-exclude = [
    "name = 'Notification'",
    "name = 'xfce4-notifyd'",
    "class_g = 'Firefox' && argb",
    "class_g = 'Synapse'",
    "class_g ?= 'Notify-osd'",
    "class_g ?= 'Cairo-dock'",
    "class_g ?= 'Xfce4-notifyd'",
    "class_g ?= 'Xfce4-power-manager'",
    "_GTK_FRAME_EXTENTS@:c",
    #"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "class_g ?= 'rofi'",
    "name = 'polybar'",
    "class_g ?= 'polybar'"
];
shadow-ignore-shaped = false;

inactive-opacity = 0.98;
active-opacity = 0.99;
frame-opacity = 1;
inactive-opacity-override = true;
inactive-dim = 0.05;

blur = false;

fading = true;
fade-delta = 10;
fade-in-step = 0.05;
fade-out-step = 0.05;
no-fading-openclose = true;

refresh-rate = 60;
detect-transient = true;

wintypes:
{
    tooltip =
    {
        fade = true;
        shadow = true;
        opacity = 0.95;
        focus = true;
    };
    utility =
  {
    shadow = false;
  };
};
