format = """[](fg:252)[](bg:252)$username$hostname$directory$git_branch$time[i](fg:252 bg:252)[](fg:252) $character """

add_newline=false

[username]
disabled = false
show_always = false
format = "[$user]($style)"
style_user = "fg:124 bg:252"

[hostname]
disabled = false
ssh_only = true
format = "[  $hostname]($style)"
style = "fg:222 bg:252"

[character]
use_symbol_for_status = true
success_symbol = "[ ](fg:077)"
error_symbol = "[ ✗](fg:124)"
# ﬦﬦ

[directory]
format = "[   $path]($style)"
style = "fg:124 bg:252 italic"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = "…/"
fish_style_pwd_dir_length = 252

[cmd_duration]
format = " took [$duration]($style)"
style = "039"
min_time = 1252

[time]
disabled = false
format = "[  $time]($style)"
style = "fg:238 bg:252"

[git_branch]
style = "bold fg:135 bg:252"
format = "[  $branch]($style)"

[git_status]
style = "fg:252"

[battery]
format = "with [$symbol$percentage]($style)"
full_symbol = "🔋 "

[[battery.display]]
threshold = 25
style = "bold 124"

[[battery.display]]
threshold = 50
style = "221"

[[battery.display]]
threshold = 100
style = "77"
