local cmd = vim.cmd

local g

cmd "set termguicolors"
cmd "colorscheme oceanic_material"

cmd "hi Normal                            guibg=#121214"
cmd "hi EndOfBuffer                       guifg=#121214 guibg=#121214"
cmd "hi VertSplit                         guifg=#202024 guibg=#121214"
cmd "hi StatusLine                        guifg=#0d0d0f guibg=#0d0d0f"
cmd "hi StatusLineNC                      guifg=#0d0d0f guibg=#0d0d0f"
cmd "hi SignColumn                        guibg=#121214"
cmd "hi Window                            guibg=#18181a"
cmd "hi Quote                             guibg=#18181a"
cmd "hi CocFloating                       guibg=#18181a"
cmd "hi Pmenu                             guifg=#a0a0a0 guibg=#202024"
cmd "hi PmenuSel                          guifg=#0d0d0f guibg=#C0A1A6"
cmd "hi PmenuSbar                         guibg=#303034"
cmd "hi LineNr                            guibg=#121214 gui=italic"
cmd "hi CocFloating                       guibg=#303034"
cmd "hi Quote                             guibg=#18181a"
cmd "hi CocErrorSign                      guifg=#dc2430 guibg=#202024"
cmd "hi CocWarningSign                    guifg=#e0b040 guibg=#202024"
cmd "hi CocInfoSign                       guifg=#80c0f0 guibg=#202024"
cmd "hi CocHintSign                       guifg=#d0d0d4 guibg=#202024"
cmd "hi LspDiagnosticSignError            guifg=#dc2430 guibg=#121214"
cmd "hi LspDiagnosticSignWarning          guifg=#e0b040 guibg=#121214"
cmd "hi LspDiagnosticSignInformation      guifg=#80c0f0 guibg=#121214"
cmd "hi LspDiagnosticSignHint             guifg=#d0d0d4 guibg=#121214"
cmd "hi LineNr                            guifg=#34343a"
cmd "hi FoldColumn                        guibg=#121214"
cmd "hi Folded                            guibg=#121214"
cmd "hi CursorLine                        guibg=#18181a"
cmd "hi Operator                          guibg=NONE"
cmd "hi Comment                           gui=italic"
cmd "hi Keyword                           gui=bold"
cmd "hi CursorLineNr                      guifg=#C0A1C6 guibg=#202024 gui=bold,italic"
cmd "hi NvimTreeFolderIcon                guifg=#C0A1C6"
cmd "hi NvimTreeFolderName                guifg=#6EACEB"
cmd "hi NvimTreeNormal                    guibg=#0d0d0f"
cmd "hi NvimTreeEndOfBuffer               guifg=#0d0d0f guibg=#0d0d0f"
cmd "hi NvimTreeStatusLine                guifg=#0d0d0f guibg=#0d0d0f"
cmd "hi NvimTreeStatuslineNC              guifg=#0d0d0f guibg=#0d0d0f"
cmd "hi NvimTreeVertSplit                 guifg=#121214 guibg=#0d0d0f"
cmd "hi NvimTreeLspDiagnosticsError       guifg=#dc2430 guibg=#0d0d0f"
cmd "hi NvimTreeLspDiagnosticsWarning     guifg=#e0b040 guibg=#0d0d0f"
cmd "hi NvimTreeLspDiagnosticsInformation guifg=#80c0f0 guibg=#0d0d0f"
cmd "hi NvimTreeLspDiagnosticsHint        guifg=#d0d0d4 guibg=#0d0d0f"

