
[module/alsa]
type = internal/alsa

;;master-soundcard = default
;;speaker-soundcard = default
;;headphone-soundcard = default
;;master-mixer = Master

;;speaker-mixer = Speaker
;;headphone-mixer = Headphone
;;headphone-id = 9

;;mapped = true
;;interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.BGalsa}

format-muted = <label-muted>
format-muted-prefix = "婢"
format-muted-prefix-font = 2
format-muted-background = ${color.BGalsa}

label-volume = %percentage%%
label-muted = " Mute"

ramp-volume-0 = 奄
ramp-volume-1 = 奄
ramp-volume-2 = 奄
ramp-volume-3 = 奔
ramp-volume-4 = 奔
ramp-volume-5 = 奔
ramp-volume-6 = 墳
ramp-volume-7 = 墳
ramp-volume-8 = 墳
ramp-volume-9 = 墳
ramp-volume-foreground = ${color.GREEN}
ramp-volume-font = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery

full-at = 95
battery = BAT0
adapter = AC0

poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 2
format-charging-prefix-foreground = ${color.PINK}
format-charging-background = ${color.transparent}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.transparent}

label-charging = %percentage%%
label-discharging = %percentage%%

format-full = "FULL"
format-full-prefix = " "
format-full-prefix-font = 3
format-full-prefix-foreground = ${color.GREEN}
format-full-foreground = ${color.foreground}
format-full-background = ${color.transparent}
label-full = %percentage%%

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-foreground = ${color.YELLOW}
ramp-capacity-font = 3

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-foreground = ${color.GREEN}
animation-charging-font = 3
animation-charging-framerate = 700

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/cpu]
type = internal/cpu

interval = 0.5

format = <bar-load>
format-prefix = "   "
format-prefix-font = 3
format-prefix-foreground = ${color.foreground}
format-background = ${color.transparent}

label = "%percentage:2%%"

bar-load-width = 35
bar-load-foreground-0 = #A071A6
bar-load-foreground-1 = #AA6492
bar-load-foreground-2 = #B4577F
bar-load-foreground-3 = #BE4B6B
bar-load-foreground-4 = #C83E57
bar-load-foreground-5 = #D23144
bar-load-foreground-6 = #DC2430
bar-load-indicator = ■
bar-load-indicator-font = 3
bar-load-fill = ■
bar-load-fill-font = 3
bar-load-empty = ■
bar-load-empty-font = 3
bar-load-empty-foreground = #202024

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date

interval = 1.0
time = %H:%M • %b %d, %G

format = <label>
format-prefix = "   "
format-prefix-font = 2
format-prefix-foreground = ${color.foreground}
format-background = ${color.transparent}

label = %time%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory

interval = 3

format = <bar-used>
format-background = ${color.transparent}

format-prefix = "﬙   "
format-prefix-font = 2
format-prefix-foreground = ${color.foreground}

label = "%percentage_used:2%%"

bar-used-width = 35
bar-used-foreground-0 = #A071A6
bar-used-foreground-1 = #AA6492
bar-used-foreground-2 = #B4577F
bar-used-foreground-3 = #BE4B6B
bar-used-foreground-4 = #C83E57
bar-used-foreground-5 = #D23144
bar-used-foreground-6 = #DC2430
bar-used-indicator = ■
bar-used-indicator-font = 3
bar-used-fill = ■
bar-used-fill-font = 3
bar-used-empty = ■
bar-used-empty-font = 3
bar-used-empty-foreground = #202024

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/spotifytext]
type = custom/script

tail = false
format-prefix = "阮   "
format-prefix-foreground = ${color.GREEN}
format = <label>
exec = ~/.config/polybar/transparent/get_spotify_status.sh

[module/mpd]
type = internal/mpd

interval = 1

format-online = <label-song>
format-online-background = ${color.transparent}
format-online-prefix = " %{A1:termite --class=ncmpcpp -e ncmpcpp &:}%{A} %{A1:art &:}%{F-}    %{F-}%{A}  "
format-online-prefix-font = 3

format-playing = ${self.format-online}
format-paused = 
format-stopped =
format-stopped-background = ${color.transparent}

label-song = " %{F#a071a6}%artist% %{F-} %{F#dc2430}%title%"
label-song-maxlen = 200
label-song-ellipsis = true

label-time = (%elapsed% / %total%)

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/polyunderlines]
type = custom/script

exec = ~/.config/polybar/darktransparent/polyunderlines.sh 2>/dev/null
format = <label>
label = %output%
label-padding = 0
line-size = 1
tail = true

[module/polywins]
type = custom/script

exec = ~/.config/polybar/darktransparent/polywins.sh 2>/dev/null
format = <label>
label = %output%
label-padding = 0
line-size = 1
tail = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wired-network]
type = internal/network

interface = eth0

[module/wireless-network]
type = internal/network

interface = wlan0

[module/network]
type = internal/network

interface = wlan0
interval = 1.0

accumulate-stats = true
unknown-as-up = true

format-connected = <ramp-signal> <label-connected>
format-connected-background = ${color.transparent}

format-disconnected = <label-disconnected>
format-disconnected-prefix = "睊  "
format-disconnected-prefix-font = 2
format-disconnected-prefix-foreground = ${color.RED}
format-disconnected-foreground = ${color.foreground}
format-disconnected-background = ${color.transparent}

label-connected = "%{A1:networkmanager_dmenu &:}%essid%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:}OFFLINE%{A}"

ramp-signal-0 = "直 "
ramp-signal-foreground = ${color.PURPLE}
ramp-signal-font = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/volume]
type = internal/pulseaudio

sink =
use-ui-max = false
interval = 5

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.transparent}

format-muted = <label-muted>
format-muted-prefix = "婢  "
format-muted-prefix-font = 2
format-muted-prefix-foreground = ${color.RED}
format-muted-background = ${color.transparent}

label-muted = "MUTED"
label-muted-foreground = ${color.foreground}

ramp-volume-0 = "奄 "
ramp-volume-1 = "奄 "
ramp-volume-2 = "奄 "
ramp-volume-3 = "奔 "
ramp-volume-4 = "奔 "
ramp-volume-5 = "奔 "
ramp-volume-6 = "墳 "
ramp-volume-7 = "墳 "
ramp-volume-8 = "墳 "
ramp-volume-9 = "墳 "
ramp-volume-font = 2
ramp-volume-foreground = ${color.BLUE}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/temperature]
type = internal/temperature

interval = 1

thermal-zone = 0
warn-temperature = 90

units = true

format = <ramp>
format-warn = <ramp>

label = %temperature-c%
label-foreground = #606060

label-warn = "%temperature-c%"
label-warn-prefix-foreground = ${color.RED}
label-warn-foreground = #0d0d0f
label-warn-background = ${color.transparent}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-font = 2
ramp-0-foreground = #A071A6
ramp-1-foreground = #AA6492
ramp-2-foreground = #B4577F
ramp-3-foreground = #BE4B6B
ramp-4-foreground = #C83E57
ramp-5-foreground = #D23144
ramp-6-foreground = #DC2430

format-padding = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/keyboard]
type = internal/xkeyboard

blacklist-1 = scroll lock

format = <label-layout> <label-indicator>
format-prefix = " "
format-prefix-font = 2
format-prefix-foreground = ${color.PURPLE}

label-layout = %name%
label-indicator-on = " %name%"
label-indicator-on-foreground = ${color.AC}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/openbox]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

format = <label-state>
format-background = ${color.transparent}
format-font = 0

label-monitor = %name%

label-active = %icon%
label-active-foreground = ${color.RED}
label-active-background = #A071A6

label-occupied = %icon%

label-urgent = %icon%
label-urgent-foreground = ${color.GREEN}

label-empty = %icon%
label-empty-foreground = #404040

label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1 
label-empty-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/obox-pad]
type = custom/text

content = -
content-foreground = ${color.BGopenbox}
content-background = ${color.BGopenbox}
content-padding = 2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/menu]
type = custom/text

content = ""
content-font = 2
content-background = ${color.BGmenu}
content-foreground = ${color.FGmenu}
content-padding = 2

click-left = ~/.config/rofi/bin/launcher &
;;click-middle = path_to_script
;;click-right = path_to_script

;;scroll-up = path_to_script
;;scroll-down = path_to_script

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/htop]
type = custom/text

content = "%{T3}%{T-}"
content-background = ${color.BGhtop}
content-foreground = ${color.FGhtop}
content-padding = 2

click-left = termite --class=htop -e htop &
;;click-middle = path_to_script
;;click-right = path_to_script

;;scroll-up = path_to_script
;;scroll-down = path_to_script

[module/ranger]
type = custom/text

content = "%{T3}%{T-}"
content-background = ${color.BGnautilus}
content-foreground = ${color.FGnautilus}
content-padding = 2

click-left = termite --class=ranger -e ranger &

[module/term]
type = custom/text

content = "%{T3}%{T-}"
content-background = ${color.BGterm}
content-foreground = ${color.FGterm}
content-padding = 2

click-left = termite -d $HOME &
;;click-middle = path_to_script
;;click-right = path_to_script

;;scroll-up = path_to_script
;;scroll-down = path_to_script

[module/vim]
type = custom/text

content = "%{T3}%{T-}"
content-foreground = ${color.FGvim}
content-background = ${color.BGvim}
content-padding = 2
click-left = termite --class=vim -d $HOME -e 'bash -c "vim ~ && bash"' --hold &

[module/ncmp]
type = custom/text

content = "%{T4}ﭵ"
content-font = 3
content-background = ${color.BGncmpcpp}
content-foreground = ${color.FGncmpcpp}
content-padding = 2

click-left = termite --class=ncmpcpp -d $HOME -e ncmpcpp &

[module/vis]
type = custom/text

content = ﱨ
content-font = 3
content-background = ${color.BGvis}
content-foreground = ${color.FGvis}
content-padding = 2

click-left = termite --class=vis -d $HOME -e vis &

[module/cover]
type = custom/text

content =  
content-font = 3
content-background = ${color.BGcover}
content-foreground = ${color.FGcover}
content-padding = 2

click-left = cmusCoverViewer &

[module/pulseeffects]
type = custom/text

content = 龍
content-font = 3
content-background = ${color.BGpeff}
content-foreground = ${color.FGpeff}
content-padding = 2

click-left = pulseeffects &

[module/spotify]
type = custom/text

content = "%{T4}阮"
content-font = 3
content-foreground = ${color.FGspot}
content-background = ${color.BGspot}
content-padding = 2

click-left = termite --class=spotify -d $HOME -e spotify &

[module/arch]
type = custom/text

content = "%{T3}%{T-}"
content-background = ${color.BGarch}
content-foreground = ${color.FGarch}
content-padding = 2
click-left = termite --class=fetch -d $HOME -e 'bash -c "rsarfetch && bash"' --hold &

[module/sysmenu]
type = custom/text

content = 
content-font = 2
content-background = ${color.BGsysmenu}
content-foreground = #e0e0ea
content-padding = 2

click-left = ~/.config/rofi/bin/powermenu

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pad]
type = custom/text
content = 
content-foreground = ${color.foreground}
content-background = ${color.transparent}
content-padding = 1

