
;
; Empty.
;

[module/empty]
type = custom/text

content = " "
content-foreground = ${colour.transparent}
content-font       = 0

[module/sep]
type = custom/text

content = "    "
content-foreground = ${colour.transparent}
content-font       = 0

;
; Workspaces.
;

[module/openbox]
type = internal/xworkspaces

pin-workspaces = false
enable-click   = true
enable-scroll  = false

format = " <label-state> "

label-monitor  = %icon%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.main-bg}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.DARKRED}

label-active-padding   = 2
label-urgent-padding   = 2
label-occupied-padding = 2
label-empty-padding    = 2

icon-0 = A;A
icon-1 = B;B
icon-2 = C;C
icon-3 = D;D
icon-4 = E;E
icon-5 = F;F
icon-6 = G;G
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

[module/bspwm]
type = internal/bspwm

fuzzy-match = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10
ws-icon-10 = 11;11
ws-icon-11 = 12;12
ws-icon-12 = 13;13
ws-icon-13 = 14;14
ws-icon-14 = 15;15

pin-workspaces = true
enable-click   = true
enable-scroll  = true

format = <label-state>
format-font       = 0

label-monitor  = %name%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.DARKRED}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.GRAY}

label-active-padding   = 1
label-urgent-padding   = 1
label-occupied-padding = 1
label-empty-padding    = 1

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

;
; Active window title.
;

[module/title]
type = internal/xwindow

format = <label>

format-prefix = "     "
format-prefix-foreground = ${colour.highlight}

label = %title%
label-maxlen = 62

label-empty = Desktop
label-empty-foreground = ${colour.GRAY}

;
; Stats.
;

[module/cpu]
type = internal/cpu

interval = 0.5

format = "   <label> "
format-foreground = ${colour.RED}
label = "%percentage:2%%"
label-foreground = ${colour.pill-fg}

[module/ram]
type = internal/memory

interval = 0.5

format = " ﬙  <label> " 
format-foreground = ${colour.ORANGE}
label = "%percentage_used:2%%"
label-foreground = ${colour.pill-fg}

[module/temp]
type = internal/temperature

interval = 0.5

thermal-zone = 0
warn-temperature = 90
units = true

format = "   <label> "
format-warn = "   <label-warn> "
format-foreground = ${colour.YELLOW}
format-warn-foreground = ${colour.YELLOW}
label = "%temperature-c%"
label-warn = "%temperature-c%"
label-foreground = ${colour.pill-fg}
label-warn-foreground = ${colour.RED}

;
; Music.
;

[module/mpd]
type = custom/script

tail = false

format-prefix = " %{A1:kitty --class=ncmpcpp -e ncmpcpp &:}   %{A}%{A1:art &:}%{F-}   %{F-}%{A}  "

format = <label>
exec = ~/.config/polybar/scripts/get_mpd_status.sh

interval = 0.5

[module/spotify]
type = custom/script

tail = false

format-prefix = "阮  %{F-} "
format-prefix-foreground = ${colour.GREEN}

format = <label>
exec = ~/.config/polybar/scripts/get_spotify_status.sh

interval = 0.5

[module/chrome]
type = custom/script

tail = false

format-prefix = "   %{F-} "
format-prefix-foreground = ${colour.RED}

format = <label>
exec = ~/.config/polybar/scripts/get_youtube_status.sh

interval = 0.5

[module/battery]
type = internal/battery

full-at = 95
battery = BAT0
adapter = AC0

poll-interval = 2

time-format = %H:%M

format-charging = "   <label-charging>"
format-charging-foreground = ${colour.GREEN}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colour.GREEN}
label-charging = "%percentage%%"
label-discharging = "%percentage%%"
label-charging-foreground = ${colour.pill-fg}
label-discharging-foreground = ${colour.pill-fg}

format-full = "   <label-full>"
format-full-foreground = ${colour.battery-4}
label-full = FULL
label-full-foreground = ${colour.pill-fg}

ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "

animation-charging-framerate = 700

[module/volume]
type = internal/pulseaudio

sink =
use-ui-max = false
interval = 5

format-volume = " 墳 <label-volume> "
format-volume-foreground = ${colour.INDIGO}
label-volume = "%percentage:3%%"
label-volume-foreground = ${colour.pill-fg}
format-muted = " 婢  <label-muted> "
format-muted-foreground = ${colour.INDIGO}
label-muted = MUTED
label-muted-foreground = #707074

[module/brightness]
type = internal/xbacklight

card = intel_backlight

format = <ramp>

ramp-0 = "   %percentage%% "
ramp-1 = "   %percentage%% "
ramp-2 = "   %percentage%% "
ramp-3 = "   %percentage%% "
ramp-4 = "   %percentage%% "
ramp-0-foreground = ${colour.scale-8}
ramp-1-foreground = ${colour.scale-7}
ramp-2-foreground = ${colour.scale-6}
ramp-3-foreground = ${colour.scale-5}
ramp-4-foreground = ${colour.scale-4}

[module/network]
type = internal/network

interface = wlan0
interval = 1.0

format-connected = "%{A1:networkmanager_dmenu &:} 直<label-connected> %{A} "
format-connected-foreground = ${colour.PURPLE}
format-disconnected = "%{A1:networkmanager_dmenu &:} 睊 <label-disconnected> %{A}"
format-disconnected-foreground = ${colour.PURPLE}
label-connected = "%downspeed:8%"
label-connected-foreground = ${colour.pill-fg}
label-disconnected = "DOWN"
label-disconnected-foreground = #707074

[module/uptime]
type = custom/script

format = <label>
format-prefix = "   "
format-prefix-foreground = ${colour.DARKRED}

label = "%output%"
exec = uptime -p | grep -Eo '[0-9].*'

[module/bluetooth]
type = custom/script

icon = '  '
icon-foreground = ${colour.BLUE}
exec = ~/.config/polybar/scripts/bluetooth.sh

click-left = blueman-manager

interval = 0.5

[module/gmail]
type = custom/script

exec = ~/.config/polybar/scripts/gmail/launch.py --nosound --label INBOX
tail = true

click-left = xdg-open https://gmail.com

interval = 0.5

;
; Date.
;

[module/date]
type = custom/script

format-prefix = "    "
format-prefix-foreground = ${colour.highlight}

exec = ~/.config/polybar/scripts/calendar.sh
click-left = ~/.config/polybar/scripts/calendar.sh --popup &

;
; Disk.
;

[module/disk]
type = internal/fs

mount-0 = /

interval = 5

fixed-values = true

format-mounted = <label-mounted>
format-mounted-prefix = "  "
format-mounted-prefix-foreground = ${colour.LIGHTGRAY}

label-mounted = "%{A1: thunar :}%used% USED %{F#747070}OF%{F-} %total%%{A}"

;
; Polywins.
;

[module/polywins]
type = custom/script

exec = ~/.config/polybar/scripts/polywins.sh 2>/dev/null

format = <label>

label = "  %{T2}%{F#C0A1C6}%{F-}%{T-}      %output%"
label-padding = 0

line-size = 2

tail = true

;
;
;

[module/launcher]
type = custom/text

click-left = ~/.config/rofi/bin/launcher
content = "靖"

[module/powermenu]
type = custom/text

click-left = ~/.config/rofi/bin/powermenu
content = "⏻"

