[global/wm]

margin-bottom = 0
margin-top    = 0

include-file = "~/.config/polybar/colour.ini"
include-file = "~/.config/polybar/modules.ini"

[global-opts]

font-text = "Akrobat:style=Black:size=14;4"
font-icon = "JetBrainsMonoMedium Nerd Font:size=14;2"
font-icon-larger = "JetBrainsMonoMedium Nerd Font:size=18;4"
font-icon-extraoffset = "JetBrainsMonoMedium Nerd Font:size=14;4"
font-mono = "VictorMono Nerd Font Mono:size=18;4"
font-mono-large = "VictorMono Nerd Font Mono:size=22;6"
font-mono-style = "VictorMono Nerd Font Mono:style=Bold:size=16;4"
font-mono-small = "VictorMono Nerd Font Mono:size=12;4"

pill-radius = 11
pill-height = 22
pill-y-offset = 8

bar-height = 38

; 
; Background bar.
;

[bar/background-top]

monitor = ${env:MONITOR}

bottom = false
override-redirect = false

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

border-size = 0
border-color = ${colour.main-ln}

modules-center = empty

font-0 = ${global-opts.font-text}

;
; Top bars.
;

[bar/datetime]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 7.8%
height = ${global-opts.pill-height}

offset-x = 0.2%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.transparent}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = date

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

[bar/workspaces]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 5.2%
height = ${global-opts.pill-height}

offset-x = 8.2%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top    = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = openbox

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

[bar/polywin]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 50%
height = ${global-opts.pill-height}

offset-x = 13.6%
offset-y = ${global-opts.pill-y-offset}

background = ${colour.transparent}
foreground = ${colour.main-fg}

radius-top = 0
radius-bottom = 0

line-size = 2
line-color = #000000

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

modules-left = polywins



[bar/music]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 18.8%
height = ${global-opts.pill-height}

offset-x = 60%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.transparent}

modules-right = sep mpd spotify chrome sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

[bar/cpu]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 79%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = cpu

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

[bar/mem]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 82%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = ram

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

[bar/temp]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 85%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = temp

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-small}

[bar/battery]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 88%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = battery

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-small}

[bar/bluetooth]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 91%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = bluetooth

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-small}

[bar/volume]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 94%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = volume

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

[bar/network]

monitor = ${env:MONITOR}
bottom = false
override-redirect = true

width = 2.8%
height = ${global-opts.pill-height}

offset-x = 97%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = network

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

;
; Bottom.
;

[bar/systray]

monitor = ${env:MONITOR}
bottom = true
override-redirect = true

width = 9.6%
height = ${global-opts.pill-height}

offset-x = 90.2%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.transparent}

tray-position = right
tray-maxsize = ${global-opts.pill-height} 
tray-padding = 0

modules-center = empty
