[global/wm]

margin-bottom = 0
margin-top    = 0

include-file = "~/.config/polybar/pastel/colour.ini"
include-file = "~/.config/polybar/pastel/modules.ini"

[global-opts]

font-text = "Akrobat:style=Black:size=20;4"
font-icon = "JetBrainsMonoMedium Nerd Font:size=16;2"
font-icon-larger = "JetBrainsMonoMedium Nerd Font:size=20;4"
font-icon-extraoffset = "JetBrainsMonoMedium Nerd Font:size=16;4"

pill-radius = 20
pill-height = 40
pill-y-offset = 6

bar-height = 52

; 
; Background bar.
;

[bar/background-top]

bottom = false
override-redirect = false

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

border-size = 1
border-color = ${colour.main-ln}

modules-center = empty

font-0 = ${global-opts.font-text}

[bar/background-bot]

bottom = true
override-redirect = true

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

modules-center = empty

font-0 = ${global-opts.font-text}

;
; Workspace pill.
;

;
; Date.
;

[bar/datetime]

bottom = false
override-redirect = true

width = 6.25%
height = ${global-opts.pill-height}

offset-x = 0.5%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = date

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

[bar/workspaces]

bottom = false
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 7.25%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top    = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = openbox

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Title indicator.
;

[bar/title]

bottom = false
override-redirect = true

width = 19.25%
height = ${global-opts.pill-height}

offset-x = 17.75%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

modules-left = title

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

;
; Music from MPD, Spotify, and Chrome.
;

[bar/music]

bottom = false
override-redirect = true

width = 22%
height = ${global-opts.pill-height}

offset-x = 39%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = sep mpd spotify chrome sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Battery.
;

[bar/ui]

bottom = false
override-redirect = true

width = 9.5%
height = ${global-opts.pill-height}

offset-x = 73%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = sep battery sep volume sep network sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}


;
; CPU, memory, and temperature.
;

[bar/stats]

bottom = false
override-redirect = true

width = 16.5%
height = ${global-opts.pill-height}

offset-x = 83%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = sep disk sep cpu sep ram sep temp sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

