[global/wm]

margin-bottom = 0
margin-top    = 0

include-file = "~/.config/polybar/pastel/colour.ini"
include-file = "~/.config/polybar/pastel/modules.ini"

[global-opts]

font-text = "Akrobat:style=Black:size=20;4"
font-icon = "JetBrainsMonoMedium Nerd Font:size=16;2"
font-icon-larger = "JetBrainsMonoMedium Nerd Font:size=20;4"
font-icon-extraoffset = "JetBrainsMonoMedium Nerd Font:size=16;4"
font-mono = "VictorMono Nerd Font Mono:size=20;4"
font-mono-large = "VictorMono Nerd Font Mono:size=24;4"
font-mono-style = "VictorMono Nerd Font Mono:style=Bold:size=18;4"

pill-radius = 20
pill-height = 40
pill-y-offset = 8

bar-height = 56

; 
; Background bar.
;

[bar/background-top]

bottom = false
override-redirect = false

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

border-size = 1
border-color = ${colour.main-ln}

modules-center = empty

font-0 = ${global-opts.font-text}

[bar/background-bot]

bottom = true
override-redirect = true

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

modules-center = empty

font-0 = ${global-opts.font-text}

;
; Workspace pill.
;

;
; Date.
;

[bar/datetime]

bottom = false
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 2%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = date

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

[bar/workspaces]

bottom = true
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 2%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top    = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = openbox

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Title indicator.
;

[bar/title]

bottom = false
override-redirect = true

width = 19.25%
height = ${global-opts.pill-height}

offset-x = 17.75%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

modules-left = title

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

;
; Music from MPD, Spotify, and Chrome.
;

[bar/music]

bottom = false
override-redirect = true

width = 22%
height = ${global-opts.pill-height}

offset-x = 12.5%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = sep mpd spotify chrome sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Battery.
;

[bar/battery]

bottom = false
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 96%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = battery

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

[bar/volume]

bottom = false
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 92%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = volume

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}

[bar/network]

bottom = false
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 88%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = network

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}

[bar/uptime]

bottom = false
override-redirect = true
 
width = 10%
height = ${global-opts.pill-height}

offset-x = 77.5%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = sep uptime sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}

[bar/bluetooth]

bottom = false
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 73.5%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.main-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = bluetooth

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}

[bar/gmail]

bottom = false
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 69.5%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.DARKRED}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = gmail

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}


;
; CPU, memory, and temperature.
;

[bar/disk]

bottom = true
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 77.5%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = sep disk sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

[bar/cpu]

bottom = true
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 88%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = cpu

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

[bar/mem]

bottom = true
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 92%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = ram

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono-large}

[bar/temp]

bottom = true
override-redirect = true

width = 3.5%
height = ${global-opts.pill-height}

offset-x = 96%
offset-y = ${global-opts.pill-y-offset}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = temp

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-mono}

;
; Polywins.
;

[bar/polywin]

bottom = true
override-redirect = true

width = 65%
height = ${global-opts.pill-height}

offset-x = 12.5%
offset-y = ${global-opts.pill-y-offset}

background = ${colour.main-bg}
foreground = ${colour.main-fg}

radius-top = 0
radius-bottom = 0

line-size = 2
line-color = #000000

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

modules-left = polywins

;
;
;

[bar/launch]

bottom = true
override-redirect = true

width = 1.1%
height = ${global-opts.pill-height}

offset-x = 0.45%
offset-y = ${global-opts.pill-y-offset}

background = ${colour.launch-bg}
foreground = ${colour.launch-fg}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = launcher

font-0 = ${global-opts.font-mono}

line-size = 2
line-color = #000000

[bar/power]

bottom = false
override-redirect = true

width = 1.1%
height = ${global-opts.pill-height}

offset-x = 0.45%
offset-y = ${global-opts.pill-y-offset}

background = ${colour.power-bg}
foreground = ${colour.power-fg}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = powermenu

font-0 = ${global-opts.font-mono}

