[global/wm]

margin-bottom = 0
margin-top    = 0

include-file = "~/.config/polybar/pastel/colour.ini"
include-file = "~/.config/polybar/pastel/modules.ini"

[global-opts]

font-text = "Akrobat:style=Black:size=20;4"
font-icon = "JetBrainsMonoMedium Nerd Font:size=16;2"
font-icon-larger = "JetBrainsMonoMedium Nerd Font:size=20;4"
font-icon-extraoffset = "JetBrainsMonoMedium Nerd Font:size=16;4"

pill-radius = 20
pill-height = 40
pill-y-offset = 10

bar-height = 60

; 
; Background bar.
;

[bar/background-top]

bottom = false
override-redirect = false

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

modules-center = empty

font-0 = ${global-opts.font-text}

[bar/background-bot]

bottom = true
override-redirect = true

width = 100%
height = ${global-opts.bar-height}

foreground = ${colour.transparent}
background = ${colour.main-bg}

modules-center = empty

font-0 = ${global-opts.font-text}

;
; Workspace pill.
;

[bar/workspaces]

bottom = false
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 0.25%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top    = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = openbox

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Title indicator.
;

[bar/title]

bottom = false
override-redirect = true

width = 26%
height = ${global-opts.pill-height}

offset-x = 10.75%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

modules-center = title

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

;
; CPU, memory, and temperature.
;

[bar/stats]

bottom = false
override-redirect = true

width = 8%
height = ${global-opts.pill-height}

offset-x = 91.75%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

radius-top   = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

modules-center = sep cpu sep ram sep temp sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Music from MPD, Spotify, and Chrome.
;

[bar/music]

bottom = false
override-redirect = true

width = 25%
height = ${global-opts.pill-height}

offset-x = 37.5%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = sep mpd spotify chrome sep

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Battery.
;

[bar/battery]

bottom = false
override-redirect = true

width = 4%
height = ${global-opts.pill-height}

offset-x = 87.5%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = battery

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Volume.
;

[bar/volume]

bottom = false
override-redirect = true

width = 4%
height = ${global-opts.pill-height}

offset-x = 83.25%
offset-y = ${global-opts.pill-y-offset}

radius-top = ${global-opts.pill-radius}
radius-bottom = ${global-opts.pill-radius}

foreground = ${colour.pill-fg}
background = ${colour.pill-bg}

modules-center = volume

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon}

;
; Date.
;

[bar/datetime]

bottom = false
override-redirect = true

width = 10%
height = ${global-opts.pill-height}

offset-x = 67.75%
offset-y = ${global-opts.pill-y-offset}

foreground = ${colour.main-fg}
background = ${colour.main-bg}

modules-center = date

font-0 = ${global-opts.font-text}
font-1 = ${global-opts.font-icon-larger}

