
;
; Empty.
;

[module/empty]
type = custom/text

content = " "
content-foreground = ${colour.transparent}
content-font       = 0

[module/sep]
type = custom/text

content = "    "
content-foreground = ${colour.transparent}
content-font       = 0

;
; Workspaces.
;

[module/openbox]
type = internal/xworkspaces

pin-workspaces = true
enable-click   = true
enable-scroll  = false

format = <label-state>

label-monitor  = %icon%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.DARKRED}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.GRAY}

label-active-padding   = 1
label-urgent-padding   = 1
label-occupied-padding = 1
label-empty-padding    = 1

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

[module/bspwm]
type = internal/bspwm

fuzzy-match = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10
ws-icon-10 = 11;11
ws-icon-11 = 12;12
ws-icon-12 = 13;13
ws-icon-13 = 14;14
ws-icon-14 = 15;15

pin-workspaces = true
enable-click   = true
enable-scroll  = true

format = <label-state>
format-font       = 0

label-monitor  = %name%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.DARKRED}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.GRAY}

label-active-padding   = 1
label-urgent-padding   = 1
label-occupied-padding = 1
label-empty-padding    = 1

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

;
; Active window title.
;

[module/title]
type = internal/xwindow

format = <label>

format-prefix = "     "
format-prefix-foreground = ${colour.highlight}

label = %title%
label-maxlen = 62

label-empty = Desktop
label-empty-foreground = ${colour.GRAY}

;
; Stats.
;

[module/cpu]
type = internal/cpu

interval = 0.5

format = " <ramp-load> "
label-foreground = ${colour.pill-fg}

ramp-load-0            = "         %percentage:2%%        "
ramp-load-1            = "         %percentage:2%%        "
ramp-load-2            = "         %percentage:2%%        "
ramp-load-3            = "         %percentage:2%%        "
ramp-load-4            = "         %percentage:2%%        "
ramp-load-5            = "         %percentage:2%%        "
ramp-load-6            = "         %percentage:2%%        "
ramp-load-7            = "         %percentage:2%%        "
ramp-load-8            = "         %percentage:2%%        "
ramp-load-0-background = ${colour.scale-0}
ramp-load-1-background = ${colour.scale-1}
ramp-load-2-background = ${colour.scale-2}
ramp-load-3-background = ${colour.scale-3}
ramp-load-4-background = ${colour.scale-4}
ramp-load-5-background = ${colour.scale-5}
ramp-load-6-background = ${colour.scale-6}
ramp-load-7-background = ${colour.scale-7}
ramp-load-8-background = ${colour.scale-8}

[module/ram]
type = internal/memory

interval = 0.5

format = <ramp-used>
label-foreground = ${colour.pill-fg}

ramp-used-0            = "       ﬙ %percentage_used:2%%        " 
ramp-used-1            = "       ﬙ %percentage_used:2%%        "
ramp-used-2            = "       ﬙ %percentage_used:2%%        "
ramp-used-3            = "       ﬙ %percentage_used:2%%        "
ramp-used-4            = "       ﬙ %percentage_used:2%%        "
ramp-used-5            = "       ﬙ %percentage_used:2%%        "
ramp-used-6            = "       ﬙ %percentage_used:2%%        "
ramp-used-7            = "       ﬙ %percentage_used:2%%        "
ramp-used-8            = "       ﬙ %percentage_used:2%%        "
ramp-used-9            = "       ﬙ %percentage_used:2%%        "
ramp-used-0-background = ${colour.scale-0}
ramp-used-1-background = ${colour.scale-1}
ramp-used-2-background = ${colour.scale-2}
ramp-used-3-background = ${colour.scale-3}
ramp-used-4-background = ${colour.scale-4}
ramp-used-5-background = ${colour.scale-5}
ramp-used-6-background = ${colour.scale-6}
ramp-used-7-background = ${colour.scale-7}
ramp-used-8-background = ${colour.scale-8}
ramp-used-9-background = ${colour.scale-8}

[module/temp]
type = internal/temperature

interval = 0.5

thermal-zone = 0
warn-temperature = 90
units = true

format = <ramp>
format-warn = <ramp>

label-foreground = ${colour.pill-fg}
label-warn-foreground = ${colour.RED}

ramp-0            = "        %temperature-c%       "
ramp-1            = "        %temperature-c%       "
ramp-2            = "        %temperature-c%       "
ramp-3            = "        %temperature-c%       "
ramp-4            = "        %temperature-c%       "
ramp-5            = "        %temperature-c%       "
ramp-6            = "        %temperature-c%       "
ramp-7            = "        %temperature-c%       "
ramp-8            = "        %temperature-c%       "
ramp-0-background = ${colour.scale-0}
ramp-1-background = ${colour.scale-1}
ramp-2-background = ${colour.scale-2}
ramp-3-background = ${colour.scale-3}
ramp-4-background = ${colour.scale-4}
ramp-5-background = ${colour.scale-5}
ramp-6-background = ${colour.scale-6}
ramp-7-background = ${colour.scale-7}
ramp-8-background = ${colour.scale-8}

;
; Music.
;

[module/mpd]
type = custom/script

tail = false

format-prefix = " %{A1:kitty --class=ncmpcpp -e ncmpcpp &:}   %{A}%{A1:art &:}%{F-}   %{F-}%{A}  "

format = <label>
exec = ~/.config/polybar/pastel/get_mpd_status.sh

interval = 0.5

[module/spotify]
type = custom/script

tail = false

format-prefix = "阮  %{F-} "
format-prefix-foreground = ${colour.GREEN}

format = <label>
exec = ~/.config/polybar/pastel/get_spotify_status.sh

interval = 0.5

[module/chrome]
type = custom/script

tail = false

format-prefix = "   %{F-} "
format-prefix-foreground = ${colour.RED}

format = <label>
exec = ~/.config/polybar/pastel/get_youtube_status.sh

interval = 0.5

[module/battery]
type = internal/battery

full-at = 95
battery = BAT0
adapter = AC0

poll-interval = 2

time-format = %H:%M

format-charging = <animation-charging>
format-charging-background = ${colour.battery-4}

format-discharging = <ramp-capacity>

format-full = "        FULL       "
format-full-foreground = ${colour.battery-f}
format-full-background = ${colour.battery-4}
label-full = %percentage%%

ramp-capacity-0 = "        %percentage%%        "
ramp-capacity-1 = "        %percentage%%        "
ramp-capacity-2 = "        %percentage%%        "
ramp-capacity-3 = "        %percentage%%        "
ramp-capacity-4 = "        %percentage%%        "
ramp-capacity-0-background = ${colour.battery-0} 
ramp-capacity-1-background = ${colour.battery-1} 
ramp-capacity-2-background = ${colour.battery-2} 
ramp-capacity-3-background = ${colour.battery-3} 
ramp-capacity-4-background = ${colour.battery-4}  
ramp-capacity-foreground   = ${colour.battery-f}

animation-charging-0 = "     %{F#EC407A}%{F-}   %percentage%%      "
animation-charging-1 = "     %{F#EC407A}%{F-}   %percentage%%      "
animation-charging-2 = "     %{F#EC407A}%{F-}   %percentage%%      "
animation-charging-3 = "     %{F#EC407A}%{F-}   %percentage%%      "
animation-charging-4 = "     %{F#EC407A}%{F-}   %percentage%%      "
animation-charging-framerate = 700

[module/volume]
type = internal/pulseaudio

sink =
use-ui-max = false
interval = 5

format-volume = <ramp-volume>

format-muted = "    婢 MUTED    "
format-muted-background = ${colour.RED}

label-volume = %percentage:3%%

ramp-volume-0 = "      奔  %percentage:3%%       "
ramp-volume-1 = "      奔  %percentage:3%%       "
ramp-volume-2 = "      奔  %percentage:3%%       "
ramp-volume-3 = "      墳  %percentage:3%%       "
ramp-volume-4 = "      墳  %percentage:3%%       "
ramp-volume-0-background = ${colour.scale-8}
ramp-volume-1-background = ${colour.scale-7}
ramp-volume-2-background = ${colour.scale-6}
ramp-volume-3-background = ${colour.scale-5}
ramp-volume-4-background = ${colour.scale-4}

[module/brightness]
type = internal/xbacklight

card = intel_backlight

format = <ramp>

ramp-0 = "        %percentage%%       "
ramp-1 = "        %percentage%%       "
ramp-2 = "        %percentage%%       "
ramp-3 = "        %percentage%%       "
ramp-4 = "        %percentage%%       "
ramp-0-background = ${colour.scale-8}
ramp-1-background = ${colour.scale-7}
ramp-2-background = ${colour.scale-6}
ramp-3-background = ${colour.scale-5}
ramp-4-background = ${colour.scale-4}

[module/network]
type = internal/network

interface = wlan0
interval = 1.0

format-connected = <ramp-signal>

format-disconnected = <label-disconnected>
format-disconnected-background = ${colour.RED}

label-connected = "%{A1:networkmanager_dmenu &:}%downspeed:8%%{A}    "
label-disconnected = "%{A1:networkmanager_dmenu &:}     睊  DOWN     %{A}"

ramp-signal-0 = "    直 %{A1:networkmanager_dmenu &:}%downspeed:8%%{A}     "
ramp-signal-1 = "    直 %{A1:networkmanager_dmenu &:}%downspeed:8%%{A}     "
ramp-signal-2 = "    直 %{A1:networkmanager_dmenu &:}%downspeed:8%%{A}     "
ramp-signal-3 = "    直 %{A1:networkmanager_dmenu &:}%downspeed:8%%{A}     "
ramp-signal-4 = "    直 %{A1:networkmanager_dmenu &:}%downspeed:8%%{A}     "
ramp-signal-0-background = ${colour.scale-8}
ramp-signal-1-background = ${colour.scale-7}
ramp-signal-2-background = ${colour.scale-6}
ramp-signal-3-background = ${colour.scale-5}
ramp-signal-4-background = ${colour.scale-4}

[module/uptime]
type = custom/script

format = <label>
format-prefix = "   "
format-prefix-foreground = ${colour.DARKRED}

label = "%output%"
exec = uptime -p | grep -Eo '[0-9].*'

[module/bluetooth]
type = custom/script

exec = ~/.config/polybar/pastel/bluetooth.sh

click-left = blueman-manager

[module/gmail]
type = custom/script

exec = ~/.config/polybar/pastel/gmail/launch.py --nosound --label INBOX
tail = true

click-left = xdg-open https://gmail.com

;
; Date.
;

[module/date]
type = custom/script

format-prefix = "    "
format-prefix-foreground = ${colour.highlight}

exec = ~/.config/polybar/pastel/calendar.sh
click-left = ~/.config/polybar/pastel/calendar.sh --popup &

;
; Disk.
;

[module/disk]
type = internal/fs

mount-0 = /

interval = 5

fixed-values = true

format-mounted = <label-mounted>
format-mounted-prefix = "  "
format-mounted-prefix-foreground = ${colour.LIGHTGRAY}

label-mounted = "%{A1: thunar :}%used% USED %{F#747070}OF%{F-} %total%%{A}"

;
; Polywins.
;

[module/polywins]
type = custom/script

exec = ~/.config/polybar/pastel/polywins.sh 2>/dev/null

format = <label>

label = "   %{T2}%{F#C0A1C6}%{F-}%{T-}      %output%"
label-padding = 0

line-size = 2

tail = true

;
;
;

[module/launcher]
type = custom/text

click-left = ~/.config/rofi/bin/launcher
content = "靖"

[module/powermenu]
type = custom/text

click-left = ~/.config/rofi/bin/powermenu
content = "⏻"

