
;
; Empty.
;

[module/empty]
type = custom/text

content = " "
content-foreground = ${colour.transparent}
content-font       = 0

[module/sep]
type = custom/text

content = "    "
content-foreground = ${colour.transparent}
content-font       = 0

;
; Workspaces.
;

[module/openbox]
type = internal/xworkspaces

pin-workspaces = true
enable-click   = true
enable-scroll  = true

format = <label-state>
format-font       = 0

label-monitor  = %name%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.DARKRED}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.GRAY}

label-active-padding   = 1
label-urgent-padding   = 1
label-occupied-padding = 1
label-empty-padding    = 1

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

[module/bspwm]
type = internal/bspwm

fuzzy-match = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10
ws-icon-10 = 11;11
ws-icon-11 = 12;12
ws-icon-12 = 13;13
ws-icon-13 = 14;14
ws-icon-14 = 15;15

pin-workspaces = true
enable-click   = true
enable-scroll  = true

format = <label-state>
format-font       = 0

label-monitor  = %name%
label-occupied = %icon%
label-urgent   = %icon%
label-active   = %icon%
label-empty    = %icon%

padding = 1

label-active-foreground = ${colour.DARKRED}
label-active-background = ${colour.highlight}
label-empty-foreground  = ${colour.GRAY}

label-active-padding   = 1
label-urgent-padding   = 1
label-occupied-padding = 1
label-empty-padding    = 1

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-8 = 9;9
icon-9 = 10;A
icon-10 = 11;B
icon-11 = 12;C
icon-12 = 13;D
icon-13 = 14;E
icon-14 = 15;F

;
; Active window title.
;

[module/title]
type = internal/xwindow

format = <label>

format-prefix = "     "
format-prefix-foreground = ${colour.highlight}

label = %title%
label-maxlen = 62

label-empty = Desktop
label-empty-foreground = ${colour.GRAY}

;
; Stats.
;

[module/cpu]
type = internal/cpu

interval = 0.5

format = <ramp-load>  <label>
label  = "%percentage:2%%"
label-foreground = ${colour.pill-fg}

ramp-load-0            = 
ramp-load-1            = 
ramp-load-2            = 
ramp-load-3            = 
ramp-load-4            = 
ramp-load-5            = 
ramp-load-6            = 
ramp-load-7            = 
ramp-load-8            = 
ramp-load-0-foreground = ${colour.scale-0}
ramp-load-1-foreground = ${colour.scale-1}
ramp-load-2-foreground = ${colour.scale-2}
ramp-load-3-foreground = ${colour.scale-3}
ramp-load-4-foreground = ${colour.scale-4}
ramp-load-5-foreground = ${colour.scale-5}
ramp-load-6-foreground = ${colour.scale-6}
ramp-load-7-foreground = ${colour.scale-7}
ramp-load-8-foreground = ${colour.scale-8}

[module/ram]
type = internal/memory

interval = 0.5

format = <ramp-used>  <label>
label  = "%percentage_used:2%%"
label-foreground = ${colour.pill-fg}

ramp-used-0            = ﬙
ramp-used-1            = ﬙
ramp-used-2            = ﬙
ramp-used-3            = ﬙
ramp-used-4            = ﬙
ramp-used-5            = ﬙
ramp-used-6            = ﬙
ramp-used-7            = ﬙
ramp-used-8            = ﬙
ramp-used-0-foreground = ${colour.scale-0}
ramp-used-1-foreground = ${colour.scale-1}
ramp-used-2-foreground = ${colour.scale-2}
ramp-used-3-foreground = ${colour.scale-3}
ramp-used-4-foreground = ${colour.scale-4}
ramp-used-5-foreground = ${colour.scale-5}
ramp-used-6-foreground = ${colour.scale-6}
ramp-used-7-foreground = ${colour.scale-7}
ramp-used-8-foreground = ${colour.scale-8}

[module/temp]
type = internal/temperature

interval = 0.5

thermal-zone = 0
warn-temperature = 90
units = true

format = <ramp>  <label>
format-warn = <ramp>  <label-warn>

label = %temperature-c%
label-warn = %temperature-c%

label-foreground = ${colour.pill-fg}
label-warn-foreground = ${colour.RED}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-5 = 
ramp-6 = 
ramp-7 = 
ramp-8 = 
ramp-0-foreground = ${colour.scale-0}
ramp-1-foreground = ${colour.scale-1}
ramp-2-foreground = ${colour.scale-2}
ramp-3-foreground = ${colour.scale-3}
ramp-4-foreground = ${colour.scale-4}
ramp-5-foreground = ${colour.scale-5}
ramp-6-foreground = ${colour.scale-6}
ramp-7-foreground = ${colour.scale-7}
ramp-8-foreground = ${colour.scale-8}

;
; Music.
;

[module/mpd]
type = custom/script

tail = false

format-prefix = " %{A1:kitty --class=ncmpcpp -e ncmpcpp &:}   %{A}%{A1:art &:}%{F-}   %{F-}%{A}  "

format = <label>
exec = ~/.config/polybar/pastel/get_mpd_status.sh

interval = 0.5

[module/spotify]
type = custom/script

tail = false

format-prefix = "阮  %{F-} "
format-prefix-foreground = ${colour.GREEN}

format = <label>
exec = ~/.config/polybar/pastel/get_spotify_status.sh

interval = 0.5

[module/chrome]
type = custom/script

tail = false

format-prefix = "   %{F-} "
format-prefix-foreground = ${colour.RED}

format = <label>
exec = ~/.config/polybar/pastel/get_youtube_status.sh

interval = 0.5

;
; Battery.
;

[module/battery]
type = internal/battery

full-at = 95
battery = BAT0
adapter = AC0

poll-interval = 2

time-format = %H:%M

format-charging = <animation-charging> <label-charging>
format-charging-prefix = " "
format-charging-prefix-foreground = ${colour.PINK}

format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%

format-full = "FULL"
format-full-prefix = " "
format-full-prefix-foreground = ${colour.GREEN}
format-full-foreground = ${colour.pill-fg}
label-full = %percentage%%

ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-0-foreground = ${colour.battery-0} 
ramp-capacity-1-foreground = ${colour.battery-1} 
ramp-capacity-2-foreground = ${colour.battery-2} 
ramp-capacity-3-foreground = ${colour.battery-3} 
ramp-capacity-4-foreground = ${colour.battery-4}  

animation-charging-0 = " "
animation-charging-1 = " "
animation-charging-2 = " "
animation-charging-3 = " "
animation-charging-4 = " "
animation-charging-foreground = ${colour.GREEN}
animation-charging-framerate = 700

;
; Volume.
;

[module/volume]
type = internal/pulseaudio

sink =
use-ui-max = false
interval = 5

format-volume = <ramp-volume> <label-volume>
format-muted = <label-muted>
format-muted-prefix = "婢  "
format-muted-prefix-foreground = ${colour.RED}

label-muted = "MUTED"
label-muted-foreground = ${colour.lowlight}

ramp-volume-0 = "奄 "
ramp-volume-1 = "奔 "
ramp-volume-2 = "奔 "
ramp-volume-3 = "墳 "
ramp-volume-4 = "墳 "
ramp-volume-0-foreground = ${colour.battery-0}
ramp-volume-1-foreground = ${colour.battery-1}
ramp-volume-2-foreground = ${colour.battery-2}
ramp-volume-3-foreground = ${colour.battery-3}
ramp-volume-4-foreground = ${colour.battery-4}

[module/network]
type = internal/network

interface = wlan0
interval = 1.0

format-connected = <ramp-signal> <label-connected>

format-disconnected = <label-disconnected>
format-disconnected-prefix = "睊  "
format-disconnected-prefix-foreground = ${colour.DARKRED}
format-disconnected-foreground = ${colour.lowlight}

label-connected = "%{A1:networkmanager_dmenu &:}%essid%%{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:}OFFLINE%{A}"

ramp-signal-0 = "直  "
ramp-signal-1 = "直  "
ramp-signal-2 = "直  "
ramp-signal-3 = "直  "
ramp-signal-4 = "直  "

ramp-signal-0-foreground = ${colour.battery-0}
ramp-signal-1-foreground = ${colour.battery-1}
ramp-signal-2-foreground = ${colour.battery-2}
ramp-signal-3-foreground = ${colour.battery-3}
ramp-signal-4-foreground = ${colour.battery-4}

;
; Date.
;

[module/date]
type = internal/date

interval = 1

time = %H:%M  •  %b %d, %G

format = <label>
format-prefix = "    "
format-prefix-foreground = ${colour.DARKRED}

label = %time%

;
; Disk.
;

[module/disk]
type = internal/fs

mount-0 = /

interval = 5

fixed-values = true

format-mounted = <label-mounted>
format-mounted-prefix = "  "
format-mounted-prefix-foreground = ${colour.GRAY}

label-mounted = "%used% USED %{F#747070}OF%{F-} %total%"
