# Created by newuser for 5.9

# environments
source ~/.config/zsh/flyctl
source ~/.config/zsh/kitty
source ~/.config/zsh/nvm
source ~/.config/zsh/ocaml
source ~/.config/zsh/python
source ~/.config/zsh/rust
source ~/.config/zsh/starship
source ~/.config/zsh/zoxide

# config
source ~/.config/zsh/aliases
source ~/.config/zsh/colours
source ~/.config/zsh/functions
source ~/.config/zsh/hooks
source ~/.config/zsh/keys
source ~/.config/zsh/opts
